services:
  db:
    container_name: db
    build: ./db
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  payment:
    container_name: payment
    build: ./payment
    ports:
      - 8001:8001
    expose:
      - 8001
    depends_on:
      - db

  web:
    container_name: web
    build: ./app
    volumes:
      - static_volume:/app/src/staticfiles
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - web
      - payment
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs
      - static_volume:/app/src/staticfiles
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

volumes:
  postgres_data:
  static_volume:
  certs:
