services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  web:
    build: .
    command: ./src/bin/run.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    expose:
      - "8000"
    depends_on:
      - db
    
  nginx:
    image: nginx:1.19.6-alpine
    depends_on:
      - web
    ports:
      - "80:80"
    expose:
      - "80"
      - "443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_static:/src/static

volumes:
  postgres_data:
  nginx_static:
