services:
  db:
    container_name: db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  web:
    container_name: web
    build: ./app
    volumes:
      - static_volume:/app/src/static
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - db
    
  nginx:
    container_name: nginx
    build: ./nginx
    depends_on:
      - web
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - certs:/etc/nginx/certs
      - static_volume:/app/src/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf

volumes:
  postgres_data:
  static_volume:
  certs:
